name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-release:
    name: Build and Release
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build uboot_tool
        run: make uboot_tool -j$(nproc)

      - name: Add to release
        run: gh release upload ${{github.event.release.tag_name}} uboot_tool
